name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2
        with:
          packages: ldid
          cache: true
          cache-path: ~/__cache

      - name: Build IPA
        run: |
          chmod -R 0755 ./ipabuild.sh
          ./ipabuild.sh
          ls ./build
